nextday(1,2). nextday(2,3). nextday(3,4). nextday(4,5).
nextroom(1,2). nextroom(2,3). nextroom(3,4).

course(c1,1,1).                 course(c2,3,1). course(c2,4,1). course(c3,5,1).
                course(c3,2,2). course(c3,3,2). course(c3,4,2). course(c3,5,2).
course(c4,1,3). course(c4,2,3).                 course(c5,4,3). course(c5,5,3).
course(c5,1,4). course(c5,2,4). course(c5,3,4). course(c5,4,4). course(c5,5,4).

sumdays(1,3). sumdays(2,2). sumdays(3,3). sumdays(4,4).
sumrooms(1,3). sumrooms(2,3). sumrooms(3,0). sumrooms(4,4). sumrooms(5,2).
